# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_linear <- function(A, B) {
    .Call(`_rcudarmadillo_solve_linear`, A, B)
}

inverse_matrix <- function(A) {
    .Call(`_rcudarmadillo_inverse_matrix`, A)
}

