# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix solver 
#' @param rows `numeric` matrix rows
#' @param cols `numeric` matrix columns
#' @param iterations `numeric` number of tries
solve_problem <- function(rows, cols, iterations) {
    .Call(`_rcudarmadillo_solve_problem`, rows, cols, iterations)
}

